concept: organization
credentialType: NutsKVKCredential
public: true
indices:
  - name: index_id
    parts:
      - path: id
  - name: index_issuer
    parts:
      - path: issuer
  - name: index_subject
    parts:
      - path: credentialSubject.id
        alias: subject
  - name: index_name_city
    parts:
      - path: credentialSubject.irma-demo.kvk.official.legalEntity
        alias: organization.name
        tokenizer: whitespaceOrExact
        transformer: cologne
      - path: credentialSubject.irma-demo.kvk.official.officeAddress
        alias: organization.city
        tokenizer: whitespaceOrExact
        transformer: cologne
